import { Toaster } from 'react-hot-toast';
import '@/app/globals.css';
import { Hanuman, IBM_Plex_Sans } from 'next/font/google';
import BlogNav from '@/components/header/blog-nav';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const geistSans = Hanuman({
  variable: '--font-geist-hanuman',
  subsets: ['khmer', 'latin'],
  weight: ['400', '700'],
});

const geistMono = IBM_Plex_Sans({
  variable: '--font-geist-ibm-plex-sans',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>{/* Add any additional head elements here */}</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black-background`}
      >
        <BlogNav />
        {/* <LenisProvider>{children}</LenisProvider> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
